# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=256)),
                ('descript', models.CharField(max_length=256)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
